# python3 -m pytest -v -k "test_init"
# python3 -m pytest -v -k "test_nn_linear"
# python3 -m pytest -v -k "test_nn_relu"
# python3 -m pytest -v -k "test_nn_sequential"
# python3 -m pytest -v -k "test_op_logsumexp"
# python3 -m pytest -v -k "test_nn_softmax_loss"
# python3 -m pytest -v -k "test_nn_layernorm"
# python3 -m pytest -v -k "test_nn_flatten"
# python3 -m pytest -v -k "test_nn_batchnorm"
# python3 -m pytest -v -k "test_nn_dropout"
# python3 -m pytest -v -k "test_nn_residual"
# python3 -m pytest -v -k "test_optim_sgd"
# python3 -m pytest -v -k "test_optim_adam"
# python3 -m pytest -v -k "flip_horizontal"
# python3 -m pytest -v -k "random_crop"
# python3 -m pytest -v -k "test_mnist_dataset"
# python3 -m pytest -v -k "test_dataloader"
python3 -m pytest -v -k "test_mlp"
