python3 -m pytest -l -v -k "nd_backend"
python3 -m pytest -l -v -k "cifar10"
python3 -m pytest -l -v -k "pad_forward"
python3 -m pytest -l -v -k "flip"
python3 -m pytest -l -v -k "dilate"
python3 -m pytest -l -v -k "op_conv and forward"
python3 -m pytest -l -v -k "op_conv and backward"
python3 -m pytest -l -v -k "kaiming_uniform"
python3 -m pytest -l -v -k "nn_conv_forward"
python3 -m pytest -l -v -k "nn_conv_backward"
python3 -m pytest -l -v -k "resnet9"
python3 -m pytest -l -v -k "test_rnn"
python3 -m pytest -l -v -k "test_lstm"
python3 -m pytest -l -v -k "ptb"
python3 -m pytest -l -v -k "language_model_implementation"
python3 -m pytest -l -v -k "language_model_training"