python3 -m pytest -v -k "(permute or reshape or broadcast or getitem) and cpu and not compact"
python3 -m pytest -v -k "(compact or setitem) and cpu"
python3 -m pytest -v -k "(ewise_fn or ewise_max or log or exp or tanh or (scalar and not setitem)) and cpu"
python3 -m pytest -v -k "reduce and cpu"
python3 -m pytest -v -k "matmul and cpu"
python3 -m pytest -v -k "(compact or setitem) and cuda"
python3 -m pytest -v -k "(ewise_fn or ewise_max or log or exp or tanh or (scalar and not setitem)) and cuda"
python3 -m pytest -v -k "reduce and cuda"
python3 -m pytest -v -k "matmul and cuda"